apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    run: mypod1
spec:
  containers:
  - image: alamfaisal654/node-web-app:latest
    name: nodewebapp
    ports:
    - containerPort: 8080
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  

